
package Departments;
import java.util.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;


class lib
        
{
 String booknm;
 String bookcat;
 String aunm;
 int count=0;
public void search(String boknm, String bokcat,String autnm) 
{       
     booknm=boknm;
     bookcat=bokcat;
     aunm=autnm;
    
    
    
     try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");            
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library","root","");        
        // Employee-> Database Name
        //root-> Username
        //""-> Password
        // Connection class is use to find the connection with mysql server        
            Statement st=con.createStatement();
            //Statement class Established the connection for insert, update, search record
            System.out.println("Connected"); 
            Scanner sc=new Scanner(System.in);
            //System.out.println("Enter Book Name to Search ");
            //String bdet=sc.nextLine();
            
            ResultSet r=st.executeQuery("Select * from book WHERE booknm='"+boknm+"'");
      
               while (r.next())
               {
                   count++;
                   String bnm=r.getString("booknm");
         
               }
               
          
              if(count>0)
            {
                System.out.println("Found");
            }
            else
            {
                System.out.println("Not Found");
            }  
           
        con.close();
        }        
        
     catch(Exception ex)
        {
            System.out.println("Server Failed"+ex);
        }
 }
    
}

public class library extends javax.swing.JFrame {

    /**
     * Creates new form library
     */
    
    
    public library() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtbooksearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bbnm = new javax.swing.JRadioButton();
        banm = new javax.swing.JRadioButton();
        bbcat = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        lblbname = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 96, 96));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 540));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbooksearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        txtbooksearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbooksearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtbooksearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 390, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search Books");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 85, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search By:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 136, 27));

        bbnm.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(bbnm);
        bbnm.setForeground(new java.awt.Color(255, 255, 0));
        bbnm.setText("Book Name");
        bbnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbnmActionPerformed(evt);
            }
        });
        jPanel1.add(bbnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 98, -1));

        banm.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(banm);
        banm.setForeground(new java.awt.Color(255, 255, 51));
        banm.setText("Author Name");
        jPanel1.add(banm, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 98, -1));

        bbcat.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(bbcat);
        bbcat.setForeground(new java.awt.Color(255, 255, 0));
        bbcat.setText("Book Category");
        jPanel1.add(bbcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 122, -1));

        jButton1.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, 20));

        lblbname.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblbname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblbname, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 170, 20));

        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Category", "Book Name", "Author Name", "Publisher Name", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 750, 250));

        jButton2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbooksearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbooksearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbooksearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //String bookdetails=txtbooksearch.getText();
       String boknm="";
       String bokcat="";
       String autnm="";
       int count=0; 
       
        
       // bdet=bookdetails;
      
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");            
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library","root","");        
            // Employee-> Database Name
            //root-> Username
            //""-> Password
            // Connection class is use to find the connection with mysql server        
            Statement st=con.createStatement();
            //Statement class Established the connection for insert, update, search record
            System.out.println("Connected"); 
            Scanner sc=new Scanner(System.in);   
            
        if (bbnm.isSelected())
        {
            boknm=txtbooksearch.getText();
            ResultSet r=st.executeQuery("Select * from book WHERE booknm='"+boknm+"'");
            while (r.next())
               {
                   count++;
                   String bnm=r.getString("booknm");
                   DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
                   model.addRow( new String[] {r.getString("bookid"),r.getString("bookcat"),r.getString("booknm"),r.getString("aunm"),r.getString("pubnm"),r.getString("price")});
                   count++;
               }     
        }
        if (banm.isSelected())
        {
            autnm=txtbooksearch.getText();
            ResultSet r=st.executeQuery("Select * from book WHERE aunm='"+autnm+"'");
            while (r.next())
               {
                   count++;
                   String anm=r.getString("aunm");
                   DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
                   model.addRow( new String[] {r.getString("bookid"),r.getString("bookcat"),r.getString("booknm"),r.getString("aunm"),r.getString("pubnm"),r.getString("price")});
                   count++;
               }     
        }
        if (bbcat.isSelected())        
        {
            bokcat=txtbooksearch.getText();
            ResultSet r=st.executeQuery("Select * from book WHERE bookcat='"+bokcat+"'");
            while (r.next())
               {
                   count++;
                   String bcat=r.getString("booknm");
                   DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
                   model.addRow( new String[] {r.getString("bookid"),r.getString("bookcat"),r.getString("booknm"),r.getString("aunm"),r.getString("pubnm"),r.getString("price")});
                   count++;                                 
               }     
        }     
             
            if (count>0)
            {
                lblbname.setText("Found");
            }
            else
            {
                lblbname.setText("Not Available");
               
            }
         con.close();
        }     
        catch(Exception ex)
        {
            System.out.println("Server Failed"+ex);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        txtbooksearch.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bbnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbnmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /*   lib ob=new lib();
         {
       ob.search();
       }   
        */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new library().setVisible(true);
           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton banm;
    private javax.swing.JRadioButton bbcat;
    private javax.swing.JRadioButton bbnm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblbname;
    private javax.swing.JTextField txtbooksearch;
    // End of variables declaration//GEN-END:variables
}
